name: Parisa Shahabinejad
tagline: Computer Engineering Student, with a Minor in Mathematics
career-objective: I am an enthusiastic computer engineering student with a keen interest in machine learning and solving complex problems using deep learning. Along with my technical skills, I also have a creative side that loves painting and playing basketball. Cats are my favorite companions as they always cheer me up.
color-theme: blue # red or blue
avatar-filename: avatar.JPG
url: parissashahabi.github.io
baseurl: /
paginate: 5
paginate_path: "/blog/page:num/"

# Social Information
social:
  email: 
    visibility: true
    mail: prisashahbi@gmail.com
  github: 
    visibility: true
    handle: parissashahabi
  linkedin: 
    visibility: true
    handle: parisa-shahabi
  twitter: 
    visibility: false
    handle: arnobdotme

# Collections
collections:
  experience:
    output: false
    sort_by: order
  education:
    output: false
    sort_by: order
  projects:
    output: false
    sort_by: order
  skills:
    output: false
    sort_by: order
  publications:
    output: true
    sort_by: year
  volunteerexperience:
    output: false
    sort_by: order
  certifications:
    output: false
    sort_by: order
  achievements:
    output: false
    sort_by: order

# About Page Options
collection_option:
  experience: 
    label: Experience
    visibility: true
  education: 
    label: Education
    visibility: true
  projects: 
    label: Projects
    visibility: true
  skills: 
    label: Skills
    visibility: true
  publications: 
    label: Publications
    visibility: false
  volunteerexperience: 
    label: Test Scores
    visibility: true
  certifications: 
    label: Online Courses
    visibility: true
  achievements: 
    label: Teaching Experience
    visibility: true

navigation:
- title: About
  url: /
- title: CV
  url: /cv
- title: Contact
  url: /contact

include:
  - _pages

exclude:
  - readme.md

# Defaults
defaults:
  - scope:
      path: ''
      type: posts
    values:
      permalink: /:categories/:year/:month/:title
      layout: post
      comments: true
  - scope:
      path: ''
      type: projects
    values:
      permalink: /projects/:title
      layout: project
      comments: false
  - scope:
      path: ''
      type: publications
    values:
      permalink: /publications/:title
      layout: publication
      comments: false

# Disqus Comment
disqus:
  shortname: academic-portfolio # Change with your own disqus shortname

# Contact Form
formspree:
  endpoint: https://formspree.io/f/xeqbbvzb

# Google Analytics
google_analytics: G-P7BRSYWSDL
